import type { Doctor } from "./types";

// Demo-only fallback data shown when the backend directory has no doctors
// yet (fresh deployment). Names are invented; locations are real Bengaluru
// localities for flavor only.
export interface MockDoctor extends Doctor {
  qualifications: string;
  yearsExperience: number;
  clinicName: string;
  locality: string;
  consultationFeeInr: number;
}

export const MOCK_DOCTORS: MockDoctor[] = [
  {
    id: "mock-doctor-1",
    name: "Dr. Ananya Rao",
    specialty: "Cardiology",
    languages: ["English", "Kannada", "Hindi"],
    consultationTypes: ["video", "chat"],
    bio: "Interventional cardiologist focused on preventive heart care and post-cardiac-event follow-up.",
    availabilityStatus: "available_now",
    averageRating: 4.8,
    qualifications: "MBBS, MD (Cardiology), DM",
    yearsExperience: 14,
    clinicName: "Bengaluru Heart Institute",
    locality: "Indiranagar, Bengaluru",
    consultationFeeInr: 900,
  },
  {
    id: "mock-doctor-2",
    name: "Dr. Karthik Nair",
    specialty: "Dermatology",
    languages: ["English", "Malayalam", "Kannada"],
    consultationTypes: ["video", "chat"],
    bio: "Treats acne, eczema, and pigmentation disorders with an emphasis on evidence-based skincare.",
    availabilityStatus: "available_now",
    averageRating: 4.6,
    qualifications: "MBBS, MD (Dermatology)",
    yearsExperience: 9,
    clinicName: "Koramangala Skin Clinic",
    locality: "Koramangala, Bengaluru",
    consultationFeeInr: 700,
  },
  {
    id: "mock-doctor-3",
    name: "Dr. Priya Menon",
    specialty: "Pediatrics",
    languages: ["English", "Tamil", "Hindi"],
    consultationTypes: ["video", "chat"],
    bio: "Pediatrician specializing in newborn care, vaccinations, and childhood growth monitoring.",
    availabilityStatus: "unavailable",
    averageRating: 4.9,
    qualifications: "MBBS, MD (Pediatrics)",
    yearsExperience: 11,
    clinicName: "Whitefield Children's Clinic",
    locality: "Whitefield, Bengaluru",
    consultationFeeInr: 650,
  },
  {
    id: "mock-doctor-4",
    name: "Dr. Suresh Gowda",
    specialty: "Orthopedics",
    languages: ["English", "Kannada"],
    consultationTypes: ["video"],
    bio: "Orthopedic surgeon treating sports injuries, joint pain, and post-fracture rehabilitation.",
    availabilityStatus: "available_now",
    averageRating: 4.5,
    qualifications: "MBBS, MS (Orthopedics)",
    yearsExperience: 17,
    clinicName: "Jayanagar Ortho Center",
    locality: "Jayanagar, Bengaluru",
    consultationFeeInr: 850,
  },
  {
    id: "mock-doctor-5",
    name: "Dr. Meera Iyer",
    specialty: "Gynecology",
    languages: ["English", "Tamil", "Kannada"],
    consultationTypes: ["video", "chat"],
    bio: "Gynecologist offering prenatal care, family planning, and menopause management.",
    availabilityStatus: "available_now",
    averageRating: 4.7,
    qualifications: "MBBS, MD (Obstetrics & Gynecology)",
    yearsExperience: 13,
    clinicName: "HSR Women's Health Clinic",
    locality: "HSR Layout, Bengaluru",
    consultationFeeInr: 800,
  },
  {
    id: "mock-doctor-6",
    name: "Dr. Arjun Reddy",
    specialty: "General Medicine",
    languages: ["English", "Telugu", "Hindi", "Kannada"],
    consultationTypes: ["video", "chat"],
    bio: "General physician for everyday illnesses, chronic disease management, and health checkups.",
    availabilityStatus: "available_now",
    averageRating: 4.4,
    qualifications: "MBBS, MD (General Medicine)",
    yearsExperience: 8,
    clinicName: "Malleshwaram Family Clinic",
    locality: "Malleshwaram, Bengaluru",
    consultationFeeInr: 500,
  },
  {
    id: "mock-doctor-7",
    name: "Dr. Lakshmi Pillai",
    specialty: "Psychiatry",
    languages: ["English", "Malayalam", "Hindi"],
    consultationTypes: ["video", "chat"],
    bio: "Psychiatrist treating anxiety, depression, and stress-related disorders through therapy and medication.",
    availabilityStatus: "unavailable",
    averageRating: 4.9,
    qualifications: "MBBS, MD (Psychiatry)",
    yearsExperience: 12,
    clinicName: "Indiranagar Mind Wellness Center",
    locality: "Indiranagar, Bengaluru",
    consultationFeeInr: 1000,
  },
  {
    id: "mock-doctor-8",
    name: "Dr. Vikram Shetty",
    specialty: "Endocrinology",
    languages: ["English", "Kannada", "Tulu"],
    consultationTypes: ["video"],
    bio: "Endocrinologist specializing in diabetes, thyroid disorders, and hormonal imbalances.",
    availabilityStatus: "available_now",
    averageRating: 4.6,
    qualifications: "MBBS, MD, DM (Endocrinology)",
    yearsExperience: 15,
    clinicName: "Rajajinagar Diabetes & Thyroid Clinic",
    locality: "Rajajinagar, Bengaluru",
    consultationFeeInr: 950,
  },
];
